version: "3"
services:
  postgres:
    build: .
    command: ["docker-entrypoint.sh", "postgres", "-c", "shared_preload_libraries=pgaudit"]
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/sql:/docker-entrypoint-initdb.d
      - ./docker/logs:/var/log/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YOUR_SECRET_PASSWORD_HERE

volumes:
  postgres-data:
